### ISSUE TITLE
Vertical alignment does not match Font Awesome icons

### ISSUE THREAD

**Issue by logological** [jpswalsh/academicons#160]
I'm trying to use Academicons alongside the latest Font Awesome icons (v5.15.3). Despite [the Academicons documentation's claim](http://jpswalsh.github.io/academicons/) that the two fonts share the same metrics, icons from the two libraries don't seem to line up vertically.  Here's a (hopefully) minimal example showing what I mean:

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Test</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons/css/academicons.min.css">
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>

    <style>
      .social-icons .social-icon {
          display: inline-flex;
          align-items: center;
          justify-content: center;
          height: 3.5rem;
          width: 3.5rem;
          background-color: #495057;
          color: #fff;
          border-radius: 100%;
          font-size: 1.5rem;
          margin-right: 0.5rem;
          text-decoration: none;
      }
    </style>
</head>

<body>
  <div class="social-icons">
    <a class="social-icon" href="#"><i class="ai ai-acmdl"></i></a>
    <a class="social-icon" href="#"><i class="fab fa-diaspora"></i></a>
    <a class="social-icon" href="#"><i class="ai ai-google-scholar"></i></a>
    <a class="social-icon" href="#"><i class="fab fa-github"></i></a>
    <a class="social-icon" href="#"><i class="ai ai-impactstory"></i></a>
  </div>
</body>
</html>
```

When this page is rendered, notice how the circles containing the Font Awesome icons are slightly higher than the ones containing the Academicons icons:

![academicons](https://user-images.githubusercontent.com/831326/121012534-1834c500-c798-11eb-86dc-1ea46fb85cc4.png)

Have I done something wrong here or is there a bug in Academicons (or in Font Awesome)?

**Comment by IlseO76** [comment]
I have just applied the code above to a web page, and in my case they align just fine:
![image](https://user-images.githubusercontent.com/66643134/128407386-0e7cbc39-699d-4bce-9aa8-80ae3eb8ef15.png)

**Comment by IlseO76** [comment]
But actually I recall now that I did have the same problem a few days back.  And if I recall correctly, but I'm not sure, the problem turned out to be that besides the font-size that I applied to all icons, a different font size was still applied to the ai-3x class that I had added to the <i></i>. But you are not using that class, so this is of no help I suppose. Nevertheless, my suggestion would be to use the browser inspector to carefully compare the CSS that is being applied to both the Fontawesome icons and the Academicons. There must be a difference there on your site (on my site there is not, as the image shows).

![icons-align](https://user-images.githubusercontent.com/66643134/128408449-54d2989e-6c8a-47cd-83c5-c10d1a0ceada.PNG)

**Comment by IlseO76** [comment]
But I guess it is still a bug if it does not work out of the box and you have to add your own CSS to compensate for the difference between Fontawesome icons and Academicons...

**Comment by IlseO76** [comment]
> There must be a difference there on your site (on my site there is not, as the image shows).

This is not true, there may be a difference between the CSS applied to both types of icons on MY site and not on yours, exactly because I (successfully) tried to solve this bug and added CSS. Sorry to not be more specific...

**Comment by logological** [comment]
> I have just applied the code above to a web page, and in my case they align just fine
[…]
> there may be a difference between the CSS applied to both types of icons on MY site and not on yours, exactly because I (successfully) tried to solve this bug and added CSS

Well, the whole point of my posting a minimal example was to demonstrate that the problem seems to be in Font Awesome itself, and not something specific to my website, and to make it easy to reproduce in isolation.  I'm also working around the alignment problem on my actual website by applying additional CSS, but it would be nice if I didn't have to.

**Comment by IlseO76** [comment]
Yeah, I get that... never mind my replies :-)

**Comment by lucjaulmes** [comment]
You might not be using the right javascript resource or there might be a bug in that specific javascript:
- When using your example javascript `<script>` tag, icons do not align
- When registering on font awesome I get a different URL `https://kit.fontawesome.com/2b51ccba33.js`, then icons align correctly. (The URL might be automatically generated per account or something, feel free to test with it anyway it’s a throw-away account.)
- When using the css link only `<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.15.3/css/all.css">` instead of javascript, icons also align, this also works with `/v6.0.0-beta1`.
- Using [Fork Awesome](https://forkaweso.me/Fork-Awesome/get-started/), which is a fork of font awesome version 4, before it became payware, icons also align correctly.

I’d actually recommend the last solution if you don’t need newer icons (from font awesome version 5 or newer), as they stuck to the simpler method of just including a css file (as academicons also does), rather than fetching and executing unknown javascript (only [the free version](https://github.com/FortAwesome/Font-Awesome) is on their repo).

**Comment by nfrerebeau** [comment]
As pointed out by @lucjaulmes, this a compatibility issue with the Font Awesome javascript resource. Inspecting your example, it appears that the svg icons are assigned a `svg-inline--fa` class with a `vertical-align` property of -.125em. This corresponds to the 3px offset with the Academicons icons.

The easiest way would be to use one of the solutions offered by @lucjaulmes.
