### ISSUE TITLE
Icon request: Clarivate (Web of Science)

### ISSUE THREAD

**Issue by SyanahWynn** [jpswalsh/academicons#184]
## Organisation

- Name: Clarivate
- Website: https://www.webofscience.com/wos/woscc/basic-search

## Scope

Since Publons has been integrated into Web of Science (WoS), researchers will start sharing their WoS account to give a clear overview of their publications and peer reviews,

## Technical checks

Confirm each of the following by checking the box. If the last two points cannot be confirmed, it is highly unlikely that the logo will be added to Academicons.

- [x] The organisation is using a logo/icon of appropriate dimensions (roughly square).
- [x] The icon can be reduced to monochrome.
- [x] A vector file (e.g. SVG, EPS, AI) or a PDF with the vector file embedded can be provided or linked to.

**Comment by machuangtao** [comment]
![webofscience](https://user-images.githubusercontent.com/47854227/186418205-e578b362-2777-429b-a826-60cf4702a8ed.svg)
I found this svg file of clarivate icon, please check if it works.

**Comment by episanty** [comment]
This should be treated as high priority.

For one, Web Of Science is one of the key literature aggregators and indexing services, and it is widely used -- particularly by institutional actors -- in a very wide range of fields and geographies.

More urgently, Clarivate has purchased Publons, and has been in the process of merging Publons into Web Of Science for quite some time. The merge is largely complete, and academic Publons profiles are no longer available -- they all redirect to Web Of Science. As such, it is now useless to use the Publons icon on an item that will attempt to link to that profile, since the link will just lead to an ugly landing page with a timer to redirect (example: https://publons.com/researcher/1556360/emilio-pisanty/).

If this suite is still under any development at all, this should probably be the highest priority. If it is not, then a clear process of transfer should be under way.

**Comment by nfrerebeau** [comment]
> If this suite is still under any development at all, this should probably be the highest priority. If it is not, then a clear process of transfer should be under way.

For the record, this project is maintained voluntarily, on our free time. This is not an on-demand service.

**Comment by episanty** [comment]
That's fair, and apologies for the tone.

But the point regarding the factors for why this is important stands.

Perhaps a good way to address this (and to help make some headway on the other open requests) would be expanding the documentation to indicate the steps that need to be taken to add new icons into a PR. The appetite is definitely there (cf. https://github.com/jpswalsh/academicons/issues/174#issuecomment-1174134346).

**Comment by nfrerebeau** [comment]
@episanty This is because I haven't published the new version yet. I'm waiting to fix #174 before, so it should be a matter of days.
